seed: 42
reproducibility': True
field_separator: "\t"
device: cuda:0
NEG_PREFIX: ''
D_PRODUCT_FIELD: D_PRODUCT
ITEM_ID_FIELD: Key_product
K_PRODUCT_TYPE_FIELD: K_PRODUCT_TYPE
Key_receipt_FIELD: Key_receipt
LINE_NUM_FIELD: LINE_NUM
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 7
QUANTITY_FIELD: QUANTITY
Q_AMOUNT_FIELD: Q_AMOUNT
Q_DISCOUNT_AMOUNT_FIELD: Q_DISCOUNT_AMOUNT
TIME_FIELD: TS_T_RECEIPT
USER_ID_FIELD: Key_receipt
dropout_prob: 0.3
embedding_size: 64
epochs: 50
eval_args:
  group_by: 'user'
  mode: full
  order: TO
  split:
    LS: valid_and_test
eval_batch_size: 1024
hidden_size: 128
load_col:
  inter:
  - K_MEMBER
  - TS_T_RECEIPT
  - LINE_NUM
  - Key_receipt
  - QUANTITY
  - Q_AMOUNT
  - Q_DISCOUNT_AMOUNT
  - Key_product
  item: 
  - Key_product
  - item_emb
  preload_weight: 
  - Key_product: item_emb
loss_type: CE
metrics:
- Recall
- MRR
- NDCG
- Hit
- Precision
- AveragePopularity
- TailPercentage
- ItemCoverage
num_layers: 1
topk: [1, 10, 50, 100]
train_batch_size: 4096
train_neg_sample_args: null
valid_neg_sample_args: null
test_neg_sample_args: null

state: 'DEBUG'
log_dir: .
checkpoint_dir: "models/type_2"
save_dataset: True
dataset: RECEIPT_LINES_TEST
# data_path: "data/processed/type_2"