purchase_receipts: "data/raw/lines_hier.pkl"
products_file: "data/processed/df_products_descriptions.pkl"
word2vec_model: "models/products_descriptions_word2vec.model"
glove_data_file: "data/external/glove.6B.100d.txt"

openai_model: gpt-3.5-turbo-0613
product_description_field: "D_PRODUCT"

batch_size: 35
words_per_item: 20
max_retries: 0
retry_delay: 10
embedding_size: 64